### ISSUE TITLE
Letters don't get pronounced when clicked on.

### ISSUE THREAD

**Issue by chimosky** [sugarlabs/iknowmyabcs#15]
Clicking on a letter should pronounce the letter but that's not the case, the logs show;
```log
Traceback (most recent call last):
  File "/home/ibiam/Activities/iknowmyabcs/page.py", line 250, in _button_release_cb
    self._play_target_sound()
  File "/home/ibiam/Activities/iknowmyabcs/page.py", line 210, in _play_target_sound
    self._media_data[self.target][1]))
  File "/home/ibiam/Activities/iknowmyabcs/utils/play_audio.py", line 72, in play_audio_from_file
    'audioconvert ! alsasink' % (file_path))
gi.repository.GLib.Error: gst_parse_error: no element "alsasink" (1)
```

Reported-by: @martinwguy

**Comment by srevinsaju** [comment]
Cannot reproduce. Possibly a missing dependency, `gstreamer0.10-alsa` on ubuntu. I have `gst-plugins-good` installed on my arch, and it works perfect.

**Comment by quozl** [comment]
Yes, but probably the `gstreamer1.0-alsa` package rather than `gstreamer0.10-alsa`.  It is as I said on [26th November on sugar-devel@](http://lists.sugarlabs.org/archive/sugar-devel/2020-November/058794.html), I'm glad.  Also affects [I Can Read](https://github.com/sugarlabs/i-can-read-activity) and [Letter Match](https://github.com/sugarlabs/lettermatch).  Workaround is to install the dependencies.  Long term, the dependencies should be listed in [README.md](https://github.com/sugarlabs/iknowmyabcs/blob/master/README.md), and the code ported to a more recent API.  [LocoSugar](https://github.com/sugarlabs/locosugar) has an example of the most recent API in [aplay.py](https://github.com/sugarlabs/locosugar/blob/master/aplay.py).

* [x] stop using ALSA sink, and port to [GStreamer playbin](https://gstreamer.freedesktop.org/documentation/playback/playbin.html?gi-language=python),
* [x] list dependencies in README.md, which will no longer include `gstreamer1.0-alsa`.

**Comment by quozl** [comment]
Cited this issue in a private reply to a developer.

**Comment by devmrfitz** [comment]
Made a pull request for this issue
